kind: pipeline
type: docker
name: arm

platform:
  arch: arm

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: kappabull/chinachuarm
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password