platform:
  arch: arm
  os: linux
steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: kappabull/chinachuarm
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password